#!/bin/bash

# Install vim plugins
if [ ! -e $HOME/.vim/bundle/Vundle.vim  ]; then
  git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi

vim +BundleInstall +qa

# Install custom bash prompt
if [ ! -d $HOME/.bash-powerline.sh ]
  git clone https://github.com/traviskn/bash-powerline/master/bash-powerline.sh ~/.bash-powerline.sh
fi

echo "Remember to use the base16 theme and get a powerline patched font"
