#!/bin/bash

# Install vim plugins
if [ ! -e $HOME/.vim/bundle/Vundle.vim  ]; then
  git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi

vim +BundleInstall +qa

# TODO: install powerline, patched font, base16 shell
