#!/bin/bash

# Install vim plugins
if [ ! -e $HOME/.vim/bundle/Vundle.vim  ]; then
  git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi

vim +BundleInstall +qa

# Download base16 shell
if [ ! -d $HOME/.config ]; then
  mkdir ~/.config
fi

if [ ! -d $HOME/.config/base16-shell ]; then
  git clone https://github.com/chriskempson/base16-shell ~/.config/base16-shell
fi

# Install powerline
powerline_path=$(python -c 'import pkgutil; print pkgutil.get_loader("powerline").filename' 2>/dev/null)
if [[ "$powerline_path" == ""   ]]; then
  pip install powerline-status
fi

# Install a patched font
if [[ ! -e /Library/Fonts/Sauce\ Code\ Pro\ Nerd\ Font\ Complete.ttf  ]]; then
  curl \
  https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/patched-fonts/SourceCodePro/Regular/complete/Sauce%20Code%20Pro%20Nerd%20Font%20Complete.ttf \
  -o /Library/Fonts/Sauce\ Code\ Pro\ Nerd\ Font\ Complete.ttf -s
  echo "Patched font installed!  Remember to use it in your terminal preferences"
fi
